// THE REASON THIS FILE IS HERE INSTEAD OF BEING TWO LEVELS UP IS BECAUSE CRA DOES NOT ALLOW
// RELATIVE IMPROTS FROM OUTSIDE SOURCE SO THIS IS A TEMPORARY FIX.
module.exports.SOCKET_ACTIONS = {
    JOIN_ROOM: "JOIN_ROOM",
    JOIN_ACCEPTED: "JOIN_ACCEPTED",
    LEAVE_ROOM: "LEAVE_ROOM",
    UPDATE_VALUE: "UPDATE_VALUE",
    USERS_CHANGED: "USERS_CHANGED",
    EDIT_REQUEST: "EDIT_REQUEST",
    VIEW_REQUEST: "VIEW_REQUEST",
    ACTIVE_CHANGED: "ACTIVE_CHANGED",
    UPDATE_NAME: "UPDATE_NAME",
};
module.exports.DOCUMENT_TEMPLATES = {
    BLANK: "BLANK",
    LETTER: "LETTER",
};
