// THE REASON THIS FILE IS HERE INSTEAD OF BEING TWO LEVELS UP IS BECAUSE CRA DOES NOT ALLOW
// RELATIVE IMPROTS FROM OUTSIDE SOURCE SO THIS IS A TEMPORARY FIX.
module.exports.SOCKET_ACTIONS = {
  JOIN_ROOM: "JOIN_ROOM",
  LEAVE_ROOM: "LEAVE_ROOM",
  UPDATE_VALUE: "UPDATE_VALUE",
};
