export default {
    BOLD: "bold",
    ITALIC: "italic",
    UNDERLINE: "underline",
    HEADINE_ONE: "heading-one",
    HEADING_TWO: "heading-two",
    NUMBERED_LIST: "numbered-list",
    BULLETTED_LIST: "bulleted-list",
    ALIGNMENT: "alignment",
    ALIGNMENT_TYPE: {
        ALIGN_RIGHT: "align-right",
        ALIGN_LEFT: "align-left",
        ALIGN_CENTER: "align-center",
    },
    TEXT_COLOR: "color",
    FONT: "font",
    FONT_SIZE: "fontsize",
    PARAGRAPH: "paragraph",
    LIST_ITEM: "list-item",
}