export default {
    SET_FONT : "SET_FONT",
    SET_FONT_SIZE: "SET_FONT_SIZE",
    SET_COLOR: "SET_COLOR",
    SET_BG_COLOR: "SET_BG_COLOR",
    FOCUS: "FOCUS",
    BLUR: "BLUR",
    SET_SELECTION: "SET_SELECTION"
};